version: '3.7'

services:
  redis:
    container_name: test-redis
    image: redis:4-alpine
    env_file:
      - .env
    volumes:
      - redisdata:/data
  db:
    image: mysql:latest
    container_name: test-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - data:/var/lib/mysql_data
    env_file:
      - .env
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: test-project
    command: 'python3 -Wd manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file: .env
    links:
      - db

volumes:
  data:
  redisdata:
